<?php
/**
 * This file defines *default* configuration settings for the Walking Tour
 * Displayer.
 *
 * Do not edit this file to change your per-site configuration; it could be
 * overwritten on upgrade. Use ../config.php instead.
 *
 * @file
 */
?>
